# Generated by Django 2.2.5 on 2020-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherobservation',
            name='pressure_tendency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
