# Generated by Django 2.2.5 on 2020-02-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smog', '0003_auto_20200216_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionlocation',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
