# Generated by Django 2.2.5 on 2020-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smog', '0004_pollutionlocation_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutionobservation',
            name='species_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pollutionobservation',
            unique_together={('pollution_location', 'species_code', 'time_stamp')},
        ),
    ]
